# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\"\x93\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1e\n\x05genre\x18\x04 \x01(\x0e\x32\x0f.Book.GenreType\x12\x0c\n\x04year\x18\x05 \x01(\x05\"0\n\tGenreType\x12\n\n\x06HORROR\x10\x00\x12\t\n\x05\x44RAMA\x10\x01\x12\x0c\n\x08THRILLER\x10\x02\"(\n\x11\x43reateBookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\x05\"(\n\x12\x43reateBookResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\t\"H\n\x0fGetBookResponse\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.BookH\x00\x88\x01\x01\x12\x12\n\nstatusCode\x18\x02 \x01(\tB\x07\n\x05_book\"\x96\x01\n\rInventoryItem\x12\x13\n\x0binventoryNo\x18\x01 \x01(\x05\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12)\n\x06status\x18\x05 \x01(\x0e\x32\x19.InventoryItem.StatusType\"\"\n\nStatusType\x12\t\n\x05\x61vail\x10\x00\x12\t\n\x05taken\x10\x01\x42\n\n\x08\x62ookName2w\n\x10InventoryService\x12\x35\n\ncreateBook\x12\x12.CreateBookRequest\x1a\x13.CreateBookResponse\x12,\n\x07getBook\x12\x0f.GetBookRequest\x1a\x10.GetBookResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=15
  _BOOK._serialized_end=162
  _BOOK_GENRETYPE._serialized_start=114
  _BOOK_GENRETYPE._serialized_end=162
  _CREATEBOOKREQUEST._serialized_start=164
  _CREATEBOOKREQUEST._serialized_end=204
  _GETBOOKREQUEST._serialized_start=206
  _GETBOOKREQUEST._serialized_end=236
  _CREATEBOOKRESPONSE._serialized_start=238
  _CREATEBOOKRESPONSE._serialized_end=278
  _GETBOOKRESPONSE._serialized_start=280
  _GETBOOKRESPONSE._serialized_end=352
  _INVENTORYITEM._serialized_start=355
  _INVENTORYITEM._serialized_end=505
  _INVENTORYITEM_STATUSTYPE._serialized_start=459
  _INVENTORYITEM_STATUSTYPE._serialized_end=493
  _INVENTORYSERVICE._serialized_start=507
  _INVENTORYSERVICE._serialized_end=626
# @@protoc_insertion_point(module_scope)
